theme: jekyll-theme-minimal

title: Alexandra Gallyas-Sanhueza

description: PhD student at Cornell University. 

logo: https://github.com/AlexandraGallyas/AlexandraGallyas.github.io/blob/master/ag753.jpg?raw=true

<i class="ai ai-google-scholar-square ai-3x"></i>


# choose markdown version
markdown: kramdown

email: ag753@cornell.edu

