theme: jekyll-theme-minimal

title: Alexandra Gallyas-Sanhueza

logo: https://github.com/AlexandraGallyas/AlexandraGallyas.github.io/blob/master/ag753.jpg?raw=true

# choose markdown version
markdown: kramdown

email: ag753@cornell.edu
