theme: jekyll-theme-minimal

title: Alexandra Gallyas-Sanhueza

description: PhD student at Cornell University. 

logo: https://github.com/AlexandraGallyas/AlexandraGallyas.github.io/blob/master/ag753.jpg?raw=true

scholar: https://scholar.google.com/citations?user=qXtU5XwAAAAJ&hl=en

resume: https://github.com/AlexandraGallyas/AlexandraGallyas.github.io/blob/master/Alexandra_Gallyas_Sanhueza_resume.pdf?raw=true

# choose markdown version
markdown: kramdown

email: ag753@cornell.edu

